actual-budget: Add logging to backup/restore cronjobs

diff --git a/charts/actual-budget/templates/cronjob-backup.yaml b/charts/actual-budget/templates/cronjob-backup.yaml
--- a/charts/actual-budget/templates/cronjob-backup.yaml
+++ b/charts/actual-budget/templates/cronjob-backup.yaml
@@ -33,6 +33,7 @@ spec:
                     exit 1
                   fi
                   tar -czf /backup/actualbudget-backup.tar.gz -C /data .
+                  echo "Created backup archive /backup/actualbudget-backup.tar.gz"
               volumeMounts:
                 - name: data
                   mountPath: /data
@@ -54,6 +55,11 @@ spec:
                     --name {{ .Values.backup.objectName }} \
                     --file /backup/actualbudget-backup.tar.gz \
                     --force
+                  if [ $? -ne 0 ]; then
+                    echo "Backup upload failed" >&2
+                    exit 1
+                  fi
+                  echo "Backup successfully uploaded to OCI Object Storage"
               volumeMounts:
                 - name: backup
                   mountPath: /backup
diff --git a/charts/actual-budget/templates/cronjob-restore.yaml b/charts/actual-budget/templates/cronjob-restore.yaml
--- a/charts/actual-budget/templates/cronjob-restore.yaml
+++ b/charts/actual-budget/templates/cronjob-restore.yaml
@@ -33,6 +33,11 @@ spec:
                     --bucket-name {{ .Values.backup.bucket }} \
                     --name {{ .Values.backup.objectName }} \
                     --file /restore/actualbudget-backup.tar.gz
+                  if [ $? -ne 0 ]; then
+                    echo "Backup download failed" >&2
+                    exit 1
+                  fi
+                  echo "Backup successfully downloaded from OCI Object Storage"
               volumeMounts:
                 - name: restore
                   mountPath: /restore
@@ -46,6 +51,7 @@ spec:
                   set -eu
                   rm -rf /data/*
                   tar -xzf /restore/actualbudget-backup.tar.gz -C /data
+                  echo "Successfully restored actualbudget data to /data"
               volumeMounts:
                 - name: data
                   mountPath: /data
